"use client";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Save, LogOut, Mail } from 'lucide-react';
export default function CustomerTools({ id, email, role, initialNote, sessions }: { id:string;email:string;role:string;initialNote:string;sessions:number }) {
  const [note,setNote]=useState(initialNote),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
  const router=useRouter();
  async function act(action:string){setBusy(true);setMessage('');setError('');try{const response=await fetch(`/api/admin/users/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,note})}),data=await response.json();if(!response.ok)throw new Error(data.error||'The action failed.');setMessage(data.message);setConfirm(false);router.refresh();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <section className="card profile-section customer-tools"><div className="section-heading"><div><span className="eyebrow">CUSTOMER SUPPORT</span><h2>Support tools</h2></div><a className="btn2" href={`mailto:${email}`}><Mail size={16}/>Email customer</a></div><form className="form" onSubmit={event=>{event.preventDefault();act('save_note');}}><label>Private support note<textarea name="note" value={note} onChange={event=>setNote(event.target.value)} maxLength={4000} rows={4} placeholder="Context and follow-up notes for administrators"/></label><small className="muted">Only administrators can see this note.</small><button className="btn" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save support note'}</button></form><div className="session-controls"><div><strong>Active sessions: {sessions}</strong><p className="muted">Signing out sessions requires the customer to sign in again. Their account and orders stay available.</p></div>{role==='admin'?<span className="muted">Administrator sessions are managed from their own account.</span>:confirm?<div><p>Sign this customer out of all devices?</p><button className="btn2" disabled={busy} onClick={()=>act('revoke_sessions')}>Confirm sign out</button><button className="btn2" disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></div>:<button className="btn2" disabled={busy||sessions===0} onClick={()=>setConfirm(true)}><LogOut size={16}/>Sign out all sessions</button>}</div>{message&&<p className="notice" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
