"use client";
import { readApiResponse } from '@/lib/api-response';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
export default function PasswordResetTools({userId}:{userId:string}){
  const[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const router=useRouter();
  async function reset(action:string,password?:string){setBusy(true);setMessage('');setError('');try{const response=await fetch(`/api/admin/users/${userId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,password})}),data=await readApiResponse(response);if(!response.ok)throw new Error(data.error);setMessage(data.message);router.refresh();return true;}catch(error){setError((error as Error).message);return false;}finally{setBusy(false);}}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),password=String(data.get('password')),confirm=String(data.get('confirmPassword'));if(password!==confirm){setError('Passwords do not match.');return;}if(await reset('reset_password',password))form.reset();}
  return <section className="card profile-section"><span className="eyebrow">ACCOUNT RECOVERY</span><h2>Reset customer password</h2><p className="muted">Send a secure reset link, or set a replacement password. A replacement password signs out all sessions and invalidates old reset links.</p><button className="btn2" disabled={busy} onClick={()=>reset('send_password_reset')}>Send password reset email</button><form className="form password-reset-form" onSubmit={submit}><div className="form-pair"><label>Replacement password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><label>Confirm replacement password<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label></div><label className="check-label"><input type="checkbox" required/>I intend to replace this customer’s password and sign them out.</label><button className="btn" disabled={busy}>Set replacement password</button></form>{message&&<p className="notice" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}

