"use client";
import {useState} from 'react';
import {CheckCircle2} from 'lucide-react';
import {paymentCatalog,paymentProviders,type PaymentProvider} from '@/lib/payment-catalog';
type Summary={active:PaymentProvider|null;gateways:{provider:PaymentProvider;configured:boolean;environment:string;verified?:boolean;verifiedAt?:string|null;verificationScope?:string|null}[]};
export default function PaymentSettings({initial,siteUrl}:{initial:Summary;siteUrl:string}){
 const [summary,setSummary]=useState(initial),[provider,setProvider]=useState<PaymentProvider>(initial.active||'cashfree'),[environment,setEnvironment]=useState(initial.gateways.find(g=>g.provider===initial.active)?.environment||'sandbox');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const selected=summary.gateways.find(g=>g.provider===provider),catalog=paymentCatalog[provider],activeGateway=summary.gateways.find(g=>g.provider===summary.active);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);await save({provider,environment,credentials:Object.fromEntries(catalog.fields.map(f=>[f.key,String(data.get(f.key)||'')]))},form);}
 async function save(body:unknown,form?:HTMLFormElement){setBusy(true);setMessage('');setError('');try{const response=await fetch('/api/admin/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(data.gateways)setSummary(data);if(!response.ok)throw new Error(data.error);setMessage(data.message);form?.reset();}catch(value){setError((value as Error).message);}finally{setBusy(false);}}
 return <section className="card settings-card"><div className="settings-heading"><div><span className="eyebrow">PAYMENT SETTINGS</span><h2>Payment gateways</h2><p className="muted">Choose a gateway and authenticate its merchant settings. Checkout uses the selected integration.</p></div><span className={`status-dot ${activeGateway?.verified?'connected':''}`}>{activeGateway?.verified?'Successfully connected':summary.active?'Saved · verification pending':'Not configured'}</span></div>
 {activeGateway?.verifiedAt&&<p className="muted fine-print">{summary.active&&paymentCatalog[summary.active].name} · {activeGateway.environment} · {activeGateway.verificationScope==='payment'?'Payment verified':'API authentication verified'} · {new Date(activeGateway.verifiedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>}
 <form className="form" onSubmit={submit}>
 <label>Payment gateway<select aria-label="Payment gateway" value={provider} disabled={busy} onChange={e=>{const next=e.target.value as PaymentProvider;setProvider(next);setEnvironment(summary.gateways.find(g=>g.provider===next)?.environment||'sandbox');setMessage('');setError('');}}>{paymentProviders.map(p=><option key={p} value={p}>{paymentCatalog[p].name}</option>)}</select></label>
 <label>Environment<select aria-label="Environment" value={environment} disabled={busy} onChange={e=>setEnvironment(e.target.value)}><option value="sandbox">Sandbox — test payments</option><option value="production">Production — live payments</option></select></label>
 <div key={provider} className="form">{catalog.fields.map(f=><label key={f.key}>{catalog.name} {f.label}<input aria-label={`${catalog.name} ${f.label}`} name={f.key} type={f.secret?'password':'text'} autoComplete={f.secret?'new-password':'off'} required disabled={busy} placeholder={selected?.configured?'Enter value to replace saved settings':f.label}/>{f.hint&&<span className="muted fine-print">{f.hint}</span>}</label>)}</div>
 <p className="muted fine-print">Credentials are encrypted on the server. Sandbox payments verify checkout without purchasing a real domain.</p>
 <button className="btn" disabled={busy}>{busy?'Saving gateway…':'Save and select gateway'}</button>
 {selected?.configured&&<button type="button" className="btn2" disabled={busy} onClick={()=>save({provider,environment,activateOnly:true})}>{summary.active===provider?'Test saved':'Validate and use saved'} {catalog.name} connection ({selected.environment})</button>}
 </form>
 <div className="notice"><b>Merchant dashboard setup</b><p>Configure this {provider==='cashfree'||provider==='razorpay'?'webhook':'callback'} URL:</p><code style={{overflowWrap:'anywhere'}}>{siteUrl}/api/payments/{provider}/{provider==='cashfree'||provider==='razorpay'?'webhook':'callback'}</code><p>{provider==='cashfree'?'Enable payment events and whitelist your website domain.':provider==='razorpay'?'Enable order.paid and payment.captured using the webhook secret above. Enable automatic payment capture in Razorpay.':'Allow your public HTTPS website and callback URL in the merchant dashboard.'}</p><a href={catalog.docs} target="_blank" rel="noreferrer">{catalog.name} setup documentation ↗</a></div>
 {message&&<p className={`notice ${message.startsWith('Successfully connected')?'connection-success':''}`} role="status">{message.startsWith('Successfully connected')&&<CheckCircle2 size={18}/>} {message}</p>}{error&&<p className="error" role="alert">{error}</p>}
 </section>;
}
