"use client";
import { readApiResponse } from '@/lib/api-response';
import {useState} from 'react';
import {CheckCircle2} from 'lucide-react';
export default function RegistrarSettings({configured,provider,verifiedAt}:{configured:boolean;provider:string;verifiedAt?:string}){
  const[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[connectedAt,setConnectedAt]=useState(verifiedAt||'');
  async function connect(body:unknown,form?:HTMLFormElement){setBusy(true);setMessage('');setError('');try{const response=await fetch('/api/admin/registrar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await readApiResponse(response);if(!response.ok)throw new Error(data.error);setMessage(data.message);setConnectedAt(data.verifiedAt);form?.reset();}catch(value){if((body as {useSaved?:boolean}).useSaved)setConnectedAt('');setError((value as Error).message);}finally{setBusy(false);}}
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);void connect({provider:data.get('provider'),apiKey:data.get('apiKey')},form);}
  return <section className="card settings-card"><div className="settings-heading"><div><span className="eyebrow">DOMAIN RESELLER</span><h2>Registrar integration</h2><p className="muted">Authenticate with your reseller before using live domain services.</p></div><span className={`status-dot ${connectedAt?'connected':''}`}>{connectedAt?'Successfully connected':configured?'Saved · verification pending':'Not configured'}</span></div>{connectedAt&&<p className="muted fine-print">API last verified: {new Date(connectedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>}<div className="provider-grid"><div className="provider-option active"><b>NameSilo</b><span>Full connector</span></div><div className="provider-option"><b>GoDaddy</b><span>Reseller access required</span></div><div className="provider-option"><b>OpenSRS</b><span>Storefront access required</span></div></div><form className="form" onSubmit={submit}><label>Domain reseller<select name="provider" aria-label="Domain reseller" defaultValue={provider||'namesilo'} disabled={busy}><option value="namesilo">NameSilo — full connector</option><option value="godaddy">GoDaddy — requires contract</option><option value="opensrs">OpenSRS — requires contract</option></select></label><label>API key / access token<input name="apiKey" type="password" autoComplete="new-password" required disabled={busy} placeholder="Enter private reseller credential"/></label><button className="btn" disabled={busy}>{busy?'Authenticating reseller…':'Validate and save integration'}</button>{(configured||connectedAt)&&<button type="button" className="btn2" disabled={busy} onClick={()=>connect({provider:'namesilo',useSaved:true})}>Test saved reseller connection</button>}{message&&<p className="notice connection-success" role="status"><CheckCircle2 size={18}/>{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</form><p className="muted fine-print">This checks API authentication. Fund the reseller account and test registration and DNS permissions before accepting live orders.</p></section>;
}


