"use client";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { EditableProfile } from '@/lib/user-profile';
export default function ProfileEditor({profile,userId}:{profile:EditableProfile;userId?:string}){
  const[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const router=useRouter();
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));setBusy(true);setMessage('');setError('');try{const response=await fetch(userId?`/api/admin/users/${userId}`:'/api/account/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,action:'update_profile'})}),result=await response.json();if(!response.ok)throw new Error(result.error);setMessage(result.message);router.refresh();}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
  return <section className="card profile-section"><span className="eyebrow">PROFILE SETTINGS</span><h2>Edit {userId?'customer':'your'} profile</h2><form className="form" onSubmit={save} key={profile.email}><div className="form-pair"><label>Full name<input name="name" defaultValue={profile.name} minLength={2} maxLength={80} autoComplete="name" required/></label><label>Email address<input name="email" type="email" defaultValue={profile.email} maxLength={254} autoComplete="email" required/></label></div><div className="form-pair"><label>Mobile number<input name="phone" type="tel" defaultValue={profile.phone} maxLength={20} autoComplete="tel" placeholder="+91 9876543210"/></label><label>Country code<input name="country" defaultValue={profile.country} maxLength={2} placeholder="IN" autoComplete="country"/></label></div><label>Address<input name="address" defaultValue={profile.address} maxLength={200} autoComplete="street-address"/></label><div className="form-pair"><label>City<input name="city" defaultValue={profile.city} maxLength={80} autoComplete="address-level2"/></label><label>State / province<input name="state" defaultValue={profile.state} maxLength={80} autoComplete="address-level1"/></label></div><label>Postal code<input name="postal_code" defaultValue={profile.postal_code} maxLength={20} autoComplete="postal-code"/></label>{!userId&&<label>Current password (required when changing email)<input name="currentPassword" type="password" maxLength={128} autoComplete="current-password"/></label>}<p className="muted fine-print">Changing email clears email verification and signs out other sessions. Saved profile details do not alter contact records on previously submitted domain orders.</p><button className="btn" disabled={busy}>{busy?'Saving profile…':'Save profile changes'}</button>{message&&<p className="notice" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</form></section>;
}
