import { createHmac, timingSafeEqual } from 'node:crypto';
import {getCashfreeSettings,type CashfreeSettings} from './settings';
const version='2025-01-01';
export async function cashfreeConfigured(){return Boolean((await getCashfreeSettings()));}
async function config(){const value=(await getCashfreeSettings());if(!value)throw new Error('Cashfree is not configured. Ask an administrator to configure payments.');return value;}
async function base(value?:CashfreeSettings){value ??= await config();return value.environment==='production'?'https://api.cashfree.com/pg':'https://sandbox.cashfree.com/pg';}
async function headers(value?:CashfreeSettings){value ??= await config();return {'Content-Type':'application/json','Accept':'application/json','x-api-version':version,'x-client-id':value.appId,'x-client-secret':value.secretKey};}
export async function validateCashfreeSettings(value:CashfreeSettings){const response=await fetch((await base(value))+'/orders/cubixtop_configuration_check',{headers:(await headers(value)),cache:'no-store',signal:AbortSignal.timeout(10000)});if(response.status===401||response.status===403)throw new Error('Cashfree rejected the App ID or Secret Key.');const data=await response.json().catch(()=>null);const authenticatedMissingOrder=response.status===404&&data?.code==='order_not_found'&&data?.type==='invalid_request_error';const authenticatedOrder=response.ok&&data?.order_id==='cubixtop_configuration_check'&&typeof data.order_status==='string';if(!authenticatedMissingOrder&&!authenticatedOrder)throw new Error('Cashfree credentials could not be validated.');return true;}
export async function createCashfreeOrder(input:{orderId:string;amount:number;customerId:string;name:string;email:string;phone:string},value?:CashfreeSettings){value ??= await config();const site=process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000';const r=await fetch((await base(value))+'/orders',{method:'POST',headers:(await headers(value)),body:JSON.stringify({order_id:input.orderId,order_amount:input.amount,order_currency:'INR',customer_details:{customer_id:input.customerId,customer_name:input.name,customer_email:input.email,customer_phone:input.phone},order_meta:{return_url:`${site}/payment/return?order_id={order_id}`,notify_url:`${site}/api/payments/cashfree/webhook`},order_note:'Cubixtop domain registration'}),cache:'no-store',signal:AbortSignal.timeout(15000)});const data=await r.json().catch(()=>({}));if(!r.ok||!data.payment_session_id)throw new Error('Cashfree could not create the payment order. Check merchant configuration.');return {...data,mode:value.environment} as {order_id:string;payment_session_id:string;order_status:string;mode:'sandbox'|'production'};}
export async function getCashfreeOrder(orderId:string,value?:CashfreeSettings){value ??= await config();const r=await fetch((await base(value))+'/orders/'+encodeURIComponent(orderId),{headers:(await headers(value)),cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('Unable to verify payment status.');return r.json() as Promise<{order_status:string;order_amount:number;order_currency:string}>;}
export async function verifyCashfreeWebhook(raw:string,timestamp:string,signature:string,secretOverride?:string){const secret=secretOverride||(await getCashfreeSettings())?.secretKey;if(!secret||!timestamp||!signature)return false;const expected=createHmac('sha256',secret).update(timestamp+raw).digest('base64');const a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b);}
