"use client";
import {useState} from 'react';
import Link from 'next/link';
import {readApiResponse} from '@/lib/api-response';
export default function ResetPassword(){
 const[done,setDone]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError('');const data=new FormData(event.currentTarget);if(data.get('password')!==data.get('confirmPassword')){setError('Passwords do not match.');return;}setBusy(true);const token=new URLSearchParams(location.search).get('token');try{const response=await fetch('/api/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reset',token,password:data.get('password')})}),body=await readApiResponse(response);if(!response.ok)throw new Error(body.error||'The password could not be reset.');setDone(true);history.replaceState(null,'','/reset-password');}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 return <main className="wrap section"><div className="auth-card card"><span className="eyebrow">SECURE RESET</span><h1>{done?'Password updated.':'Choose a new password.'}</h1>{done?<><p className="muted">Your reset link has been used. Sign in with your new password.</p><Link className="btn" href="/login">Sign in</Link></>:<><p className="muted">Use 12 to 128 characters. Reset links expire after 2 hours and can be used only once.</p><form className="form" onSubmit={submit}><label>New password<input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><label>Confirm password<input name="confirmPassword" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><button className="btn" disabled={busy}>{busy?'Updating…':'Update password'}</button>{error&&<p className="error" role="alert">{error}</p>}</form><p><Link className="text-link" href="/forgot-password">Request a new reset link</Link></p></>}</div></main>;
}
