"use client";
import Link from 'next/link';
import {useState} from 'react';
import {launchPayment} from '@/lib/payment-browser';
import CancelOrder from '../cancel-order';
type Checkout={id:string;domain:string;quote:number|null;status:string;created_at:string;payment_order_id?:string|null};
const labels:Record<string,string>={active:'Active',payment_pending:'Awaiting payment confirmation',pending_payment:'Pending payment',payment_failed:'Payment unsuccessful',provisioning:'Registering domain',manual_review:'Support review required',sandbox_paid:'Sandbox payment verified'};
export default function DomainList({initialOrders}:{initialOrders:Checkout[]}){
 const [busy,setBusy]=useState<string|null>(null),[error,setError]=useState('');
 async function resume(order:Checkout){setBusy(order.id);setError('');try{const response=await fetch('/api/payments/resume',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:order.payment_order_id})}),data=await response.json();if(!response.ok)throw new Error(data.error);if(data.returnUrl)location.assign(data.returnUrl);else await launchPayment(data,{name:'',phone:''});}catch(value){setError((value as Error).message);}finally{setBusy(null);}}
 return <>{error&&<p className="error" role="alert">{error}</p>}{!initialOrders.length?<div className="card empty-state"><h2>Your next great idea starts with a name.</h2><p className="muted">Search for a domain and your pending orders will appear here.</p><Link className="btn" href="/">Find a domain ↗</Link></div>:<div className="domain-list">{initialOrders.map(order=><article key={order.id} className="card domain-row"><div><h2>{order.domain}</h2><span className="badge">{labels[order.status]||order.status.replaceAll('_',' ')}</span><p className="muted fine-print">Created {new Date(order.created_at).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})} · {order.quote!=null?'Quote: $'+order.quote.toFixed(2)+' USD':'Final price at payment'}</p>{order.status==='sandbox_paid'&&<p className="muted fine-print">Test payment completed; no domain was purchased.</p>}{order.status==='manual_review'&&<p className="muted fine-print">Contact info@cubixtop.com before making another payment.</p>}</div><div className="domain-actions">{['pending_payment','payment_pending','payment_failed'].includes(order.status)&&<CancelOrder id={order.id} domain={order.domain}/>}{order.status==='active'?<><Link className="btn" href={'/dashboard/domains/'+encodeURIComponent(order.domain)}>Manage DNS</Link><span className="btn2">Domain active</span></>:<>{order.payment_order_id&&<Link className="btn2" href={'/payment/return?order_id='+encodeURIComponent(order.payment_order_id)}>Check payment</Link>}{order.status==='payment_pending'&&order.payment_order_id?<button className="btn" disabled={busy!==null} onClick={()=>resume(order)}>{busy===order.id?'Checking payment…':'Resume payment ↗'}</button>:!['manual_review','provisioning'].includes(order.status)&&<Link className="btn" href={'/checkout?domain='+encodeURIComponent(order.domain)}>{order.status==='sandbox_paid'?'Start another checkout ↗':'Resume order ↗'}</Link>}</>}</div></article>)}</div>}</>;
}

